#!/usr/bin/env bash
#
# Kin — one-command Cloudflare Tunnel installer.
#
# Path B (Mac / workstation / home server / behind NAT). Generates a production env
# outside the repo, decodes the Cloudflare Tunnel token into infra/tunnel/, pulls the
# prebuilt multi-arch images from GHCR, starts docker-compose.tunnel.yml, and verifies
# the local Traefik route before DNS is trusted.
#
# Usage (run from the cloned kin repo root):
#   bash scripts/install-tunnel.sh
#   bash scripts/install-tunnel.sh --yes
#   bash scripts/install-tunnel.sh --force-tunnel   # replace existing infra/tunnel files
#
# Non-interactive required env:
#   APP_HOSTNAME CLOUDFLARED_TUNNEL_TOKEN ANTHROPIC_AUTH_TOKEN ANTHROPIC_BASE_URL ANTHROPIC_MODEL
#
set -euo pipefail

COMPOSE_FILE="docker-compose.tunnel.yml"
PROJECT="${KIN_PROJECT:-kin}"
ENV_DIR="${KIN_ENV_DIR:-$HOME/kin-deploy}"
ENV_FILE="${KIN_ENV_FILE:-$ENV_DIR/secrets.env}"
REPO_ROOT="$(pwd -P)"
TUNNEL_DIR="${KIN_TUNNEL_DIR:-$REPO_ROOT/infra/tunnel}"
NONINTERACTIVE=0
START_STACK=1
FORCE_TUNNEL=0

while [ "$#" -gt 0 ]; do
  case "$1" in
    --yes | --non-interactive) NONINTERACTIVE=1 ;;
    --no-start) START_STACK=0 ;;
    --force-tunnel) FORCE_TUNNEL=1 ;;
    *) printf 'Unknown option: %s\n' "$1" >&2; exit 1 ;;
  esac
  shift
done

c_g=$'\033[1;32m'; c_y=$'\033[1;33m'; c_r=$'\033[1;31m'; c_0=$'\033[0m'
log()  { printf '%s[kin]%s %s\n' "$c_g" "$c_0" "$*"; }
warn() { printf '%s[kin]%s %s\n' "$c_y" "$c_0" "$*" >&2; }
die()  { printf '%s[kin ERROR]%s %s\n' "$c_r" "$c_0" "$*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }
rand() { openssl rand -hex 32; }
json_escape() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}
model_seed_json() {
  local base_url="$1" model="$2" escaped_base escaped_model model_id
  escaped_base="$(json_escape "$base_url")"
  escaped_model="$(json_escape "$model")"
  model_id="default/${escaped_model}"
  printf '{"default":"%s","connections":[{"id":"default","label":"Default","baseUrl":"%s","authStyle":"bearer","tokenEnv":"ANTHROPIC_AUTH_TOKEN"}],"models":[{"id":"%s","label":"%s","connection":"default","model":"%s","enabled":true,"isDefault":true,"tags":["chat"]}]}' \
    "$model_id" "$escaped_base" "$model_id" "$escaped_model" "$escaped_model"
}
sanitize_name() {
  python3 - "$1" <<'PY'
import re
import sys
host = sys.argv[1].strip().lower()
name = "kin-" + re.sub(r"[^a-z0-9_.-]+", "-", host)
name = re.sub(r"^[^a-z0-9]+", "kin-", name).strip(".-_")
print((name or "kin")[:63])
PY
}
env_has_key() {
  [ -f "$ENV_FILE" ] && grep -Eq "^$1=" "$ENV_FILE"
}
env_value() {
  local key="$1" cur=""
  if [ -f "$ENV_FILE" ] && env_has_key "$key"; then
    grep -E "^$key=" "$ENV_FILE" | tail -1 | cut -d= -f2-
    return
  fi
  eval "cur=\${$key:-}"
  printf '%s' "$cur"
}
append_env_if_missing() {
  local key="$1" value="$2"
  shift 2
  env_has_key "$key" && return 0
  {
    [ "$#" -gt 0 ] && printf '\n'
    while [ "$#" -gt 0 ]; do
      printf '%s\n' "$1"
      shift
    done
    printf '%s=%s\n' "$key" "$value"
  } >> "$ENV_FILE"
}
ask() {
  local var="$1" q="$2" def="${3:-}" cur="" ans=""
  eval "cur=\${$var:-}"
  if [ -n "$cur" ]; then printf '%s' "$cur"; return; fi
  if [ "$NONINTERACTIVE" -eq 1 ]; then
    [ -n "$def" ] && { printf '%s' "$def"; return; }
    die "missing required \$$var (non-interactive mode)"
  fi
  read -r -p "  $q${def:+ [$def]}: " ans </dev/tty || true
  printf '%s' "${ans:-$def}"
}
ensure_env_key() {
  local key="$1" prompt="$2" def="${3:-}" value=""
  value="$(env_value "$key")"
  if [ -z "$value" ]; then
    value="$(ask "$key" "$prompt" "$def")"
    [ -n "$value" ] || die "$key is required."
  fi
  append_env_if_missing "$key" "$value"
  printf '%s' "$value"
}
write_tunnel_config_from_token() {
  local host="$1" token="$2"
  python3 - "$host" "$token" "$TUNNEL_DIR/config.yml" "$TUNNEL_DIR/credentials.json" <<'PY'
import base64
import json
import pathlib
import sys

host, token, config_path, credentials_path = sys.argv[1:5]
token = token.strip()

def decode_part(part):
    part = part.strip()
    part += "=" * ((4 - len(part) % 4) % 4)
    return json.loads(base64.urlsafe_b64decode(part.encode()))

payload = None
for candidate in [token, *token.split(".")]:
    try:
        data = decode_part(candidate)
    except Exception:
        continue
    if all(k in data for k in ("a", "t", "s")):
        payload = data
        break

if payload is None:
    raise SystemExit("Cloudflare tunnel token did not decode to the expected {a,t,s} payload")

credentials = {
    "AccountTag": payload["a"],
    "TunnelID": payload["t"],
    "TunnelSecret": payload["s"],
}
pathlib.Path(credentials_path).write_text(json.dumps(credentials, separators=(",", ":")) + "\n")
pathlib.Path(config_path).write_text(
    "# Generated by scripts/install-tunnel.sh. Do not commit this file.\n"
    f"tunnel: {payload['t']}\n"
    "credentials-file: /etc/cloudflared/credentials.json\n"
    "ingress:\n"
    f"  - hostname: {host}\n"
    "    service: http://traefik:80\n"
    f"  - hostname: \"*.{host}\"\n"
    "    service: http://traefik:80\n"
    "  - service: http_status:404\n"
)
print(payload["t"])
PY
  chmod 600 "$TUNNEL_DIR/credentials.json" "$TUNNEL_DIR/config.yml"
}
read_existing_tunnel_id() {
  [ -f "$TUNNEL_DIR/credentials.json" ] || return 1
  python3 - "$TUNNEL_DIR/credentials.json" <<'PY'
import json
import sys
with open(sys.argv[1]) as f:
    print(json.load(f).get("TunnelID", ""))
PY
}
ensure_tunnel_files_can_be_replaced() {
  [ "$FORCE_TUNNEL" -eq 1 ] && return 0
  if [ -e "$TUNNEL_DIR/credentials.json" ] || [ -e "$TUNNEL_DIR/config.yml" ]; then
    die "infra/tunnel/config.yml or credentials.json already exists. Reuse it by omitting CLOUDFLARED_TUNNEL_TOKEN, or pass --force-tunnel to replace it."
  fi
}
with_timeout() {
  local seconds="$1"
  shift
  python3 - "$seconds" "$@" <<'PY'
import subprocess
import sys

timeout = int(sys.argv[1])
cmd = sys.argv[2:]
try:
    raise SystemExit(subprocess.run(cmd, timeout=timeout).returncode)
except subprocess.TimeoutExpired:
    raise SystemExit(124)
PY
}

# --- 0. preflight -----------------------------------------------------------
[ -f "$COMPOSE_FILE" ] || die "run this from the cloned kin repo root (no $COMPOSE_FILE here)."
[ -d "$TUNNEL_DIR" ] || die "missing $TUNNEL_DIR."
have openssl || die "openssl is required."
have python3 || die "python3 is required."

if ! have docker; then
  if [ "$(uname -s)" = "Linux" ] && have curl; then
    warn "Docker not found — installing via get.docker.com (requires sudo/root)."
    if [ "$(id -u)" -eq 0 ]; then
      curl -fsSL https://get.docker.com | sh
    elif have sudo; then
      curl -fsSL https://get.docker.com | sudo sh
    else
      die "Docker is missing and sudo is unavailable. Install Docker, then rerun."
    fi
  else
    die "Docker is missing. On macOS, install and start OrbStack or Docker Desktop, then rerun."
  fi
fi
docker compose version >/dev/null 2>&1 || die "docker compose plugin missing."
log "Docker $(docker --version | awk '{print $3}' | tr -d ,) ready."

mkdir -p "$ENV_DIR"
chmod 700 "$ENV_DIR"
if [ -f "$ENV_FILE" ]; then
  log "$ENV_FILE exists — reusing it (secrets preserved)."
else
  log "Generating $ENV_FILE …"
  umask 077
  printf '# Generated by install-tunnel.sh %s. SECRET — chmod 600. Do not commit.\n' "$(date -u +%FT%TZ)" > "$ENV_FILE"
fi
chmod 600 "$ENV_FILE"

# --- 1. env file ------------------------------------------------------------
APP_HOSTNAME="$(ensure_env_key APP_HOSTNAME 'App hostname, e.g. example.com or kin.example.com')"
ANTHROPIC_AUTH_TOKEN="$(ensure_env_key ANTHROPIC_AUTH_TOKEN 'LLM gateway token (ARK/Anthropic-compatible, Bearer)')"
ANTHROPIC_BASE_URL="$(ensure_env_key ANTHROPIC_BASE_URL 'Gateway base URL' 'https://ark.cn-beijing.volces.com/api/coding')"
ANTHROPIC_MODEL="$(ensure_env_key ANTHROPIC_MODEL 'Default model id (per your gateway)')"

append_env_if_missing "APP_NAME" "kin"
append_env_if_missing "APP_NAME_SANITIZED" "$(sanitize_name "$APP_HOSTNAME")"
append_env_if_missing "APP_IMAGE" "${APP_IMAGE:-ghcr.io/deeptoai-com/kin/app}"
append_env_if_missing "APP_TAG" "${APP_TAG:-latest}"
append_env_if_missing "APP_PULL_POLICY" "${APP_PULL_POLICY:-always}"
append_env_if_missing "POSTGRES_USER" "kin"
append_env_if_missing "POSTGRES_PASSWORD" "$(rand)"
append_env_if_missing "POSTGRES_DB" "kin"
append_env_if_missing "MINIO_ROOT_USER" "kin"
append_env_if_missing "MINIO_ROOT_PASSWORD" "$(rand)"
append_env_if_missing "MINIO_BUCKET" "kin-files"
append_env_if_missing "MEILI_MASTER_KEY" "$(rand)"
append_env_if_missing "BETTER_AUTH_SECRET" "$(rand)"
append_env_if_missing "JOBS_SECRET" "$(rand)"
append_env_if_missing "KIN_SECRET_KEY" "$(rand)" \
  "# Registry v2 master key for admin-pasted credentials. Generate once per deployment;" \
  "# do not rotate casually, or stored credentials must be re-entered."
append_env_if_missing "UPDATER_TOKEN" "$(rand)" \
  "# Shared secret between app and updater sidecar. Empty or missing disables online updates."
append_env_if_missing "UPDATER_PROD_ENV_DIR" "$ENV_DIR" \
  "# Directory mount for the full production env; survives inode-swapping edits."
append_env_if_missing "UPDATER_COMPOSE_ENV_FILE" "/run/updater/envd/$(basename "$ENV_FILE")"
append_env_if_missing "ANTHROPIC_DEFAULT_SONNET_MODEL" "$ANTHROPIC_MODEL"
append_env_if_missing "ANTHROPIC_DEFAULT_OPUS_MODEL" "$ANTHROPIC_MODEL"
append_env_if_missing "ANTHROPIC_DEFAULT_HAIKU_MODEL" "$ANTHROPIC_MODEL"
append_env_if_missing "CLAUDE_CODE_SUBAGENT_MODEL" "$ANTHROPIC_MODEL"
append_env_if_missing "OXY_MODELS_SEED" "$(model_seed_json "$ANTHROPIC_BASE_URL" "$ANTHROPIC_MODEL")" \
  "# Registry v2 bootstrap seed; non-secret JSON. Secrets are referenced by tokenEnv name."
append_env_if_missing "ENABLE_EMAIL_VERIFICATION" "false" \
  "# First-run UX: keep disabled unless SMTP/Resend is configured and tested."

# --- 2. tunnel credentials --------------------------------------------------
TUNNEL_TOKEN="$(env_value CLOUDFLARED_TUNNEL_TOKEN)"
if [ -n "$TUNNEL_TOKEN" ]; then
  ensure_tunnel_files_can_be_replaced
  log "Writing Cloudflare tunnel credentials/config from CLOUDFLARED_TUNNEL_TOKEN …"
  TUNNEL_ID="$(write_tunnel_config_from_token "$APP_HOSTNAME" "$TUNNEL_TOKEN")"
elif [ -f "$TUNNEL_DIR/credentials.json" ]; then
  TUNNEL_ID="$(read_existing_tunnel_id)"
  [ -n "$TUNNEL_ID" ] || die "Could not read TunnelID from $TUNNEL_DIR/credentials.json."
  log "Reusing existing tunnel credentials ($TUNNEL_ID)."
  if [ ! -f "$TUNNEL_DIR/config.yml" ] || [ "$FORCE_TUNNEL" -eq 1 ]; then
    write_tunnel_config_from_token "$APP_HOSTNAME" "$(python3 - "$TUNNEL_DIR/credentials.json" <<'PY'
import base64
import json
import sys
with open(sys.argv[1]) as f:
    c = json.load(f)
payload = {"a": c["AccountTag"], "t": c["TunnelID"], "s": c["TunnelSecret"]}
print(base64.urlsafe_b64encode(json.dumps(payload, separators=(",", ":")).encode()).decode().rstrip("="))
PY
)" >/dev/null
  fi
else
  TUNNEL_TOKEN="$(ask CLOUDFLARED_TUNNEL_TOKEN 'Cloudflare tunnel token (eyJ...)')"
  [ -n "$TUNNEL_TOKEN" ] || die "CLOUDFLARED_TUNNEL_TOKEN is required."
  log "Writing Cloudflare tunnel credentials/config …"
  TUNNEL_ID="$(write_tunnel_config_from_token "$APP_HOSTNAME" "$TUNNEL_TOKEN")"
fi

log "Tunnel ID: $TUNNEL_ID"
warn "Create Cloudflare DNS records: CNAME ${APP_HOSTNAME} -> ${TUNNEL_ID}.cfargotunnel.com (proxied) and CNAME *.${APP_HOSTNAME} -> ${TUNNEL_ID}.cfargotunnel.com (proxied)."
warn "Preview TLS note: on a full Cloudflare zone, free Universal SSL covers the zone apex and first-level subdomains only. If ${APP_HOSTNAME} is not your zone apex, enable Total TLS / Advanced Certificate for *.${APP_HOSTNAME}."

# --- 3. image + stack -------------------------------------------------------
img_ref="$(env_value APP_IMAGE):$(env_value APP_TAG)"
if [ "${KIN_CHECK_IMAGE:-0}" = "1" ]; then
  log "Pre-flight: checking image ${img_ref} is pullable…"
  if ! with_timeout 30 docker manifest inspect "$img_ref" >/dev/null 2>&1; then
    warn "Could not verify ${img_ref} within 30s. Continuing; docker compose pull will report the exact registry error if the tag is missing."
  fi
else
  log "Image pre-flight skipped for speed (${img_ref}); docker compose pull will verify it."
fi

if [ "$START_STACK" -eq 0 ]; then
  log "--no-start set; env and tunnel config are ready."
  exit 0
fi

dc() { docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" -p "$PROJECT" "$@"; }
log "Pulling images…"; dc pull
log "Starting the tunnel stack…"; dc up -d

# --- 4. local health gate ---------------------------------------------------
APP_NAME_SANITIZED="$(env_value APP_NAME_SANITIZED)"
log "Waiting for local Traefik route http://${APP_HOSTNAME}/health (via dockerproxy)…"
ok=0
for _ in $(seq 1 60); do
  tip="$(docker inspect "${APP_NAME_SANITIZED}-traefik" -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' 2>/dev/null || true)"
  if [ -n "$tip" ] && docker exec "${APP_NAME_SANITIZED}-dockerproxy" sh -c \
      "wget -qS -O /dev/null --header='Host: ${APP_HOSTNAME}' http://${tip}/health 2>&1 | grep '200 OK' >/dev/null" 2>/dev/null; then
    ok=1
    break
  fi
  sleep 5
done

if [ "$ok" -eq 1 ]; then
  log "✅ Local stack is healthy. After DNS is live, open https://${APP_HOSTNAME}"
  log "   Register the first account; email verification is off by default."
else
  warn "Stack started, but the local route did not return 200 yet."
  warn "Inspect: docker compose --env-file $ENV_FILE -f $COMPOSE_FILE -p $PROJECT ps"
  warn "Logs:    docker compose --env-file $ENV_FILE -f $COMPOSE_FILE -p $PROJECT logs -f app traefik cloudflared"
fi
