import type { Dictionary } from 'intlayer';
import { t } from 'intlayer';

/**
 * App-wide content dictionary
 * Contains navigation titles, button labels, and page titles used across the application
 */
const appContent = {
  content: {
    nav: {
      claudeChat: t({
        en: 'Kin',
        'zh-Hans': 'Kin',
        fr: 'Kin',
        ja: 'Kin',
        ko: 'Kin',
        'zh-Hant': 'Kin',
      }),
      capabilityCenter: t({
        en: 'Capability Center',
        'zh-Hans': '能力中心',
        fr: 'Centre de capacités',
        ja: '機能センター',
        ko: '기능 센터',
        'zh-Hant': '能力中心',
      }),
      skillsStore: t({
        en: 'Skills Store',
        'zh-Hans': '技能商店',
        fr: 'Boutique Skills',
        ja: 'スキルストア',
        ko: '스킬 스토어',
        'zh-Hant': '技能商店',
      }),
      mcpStore: t({
        en: 'MCP Store',
        'zh-Hans': 'MCP 商店',
        fr: 'Boutique MCP',
        ja: 'MCP ストア',
        ko: 'MCP 스토어',
        'zh-Hant': 'MCP 商店',
      }),
      documents: t({
        en: 'Documents / KB',
        'zh-Hans': '文档 / 知识库',
        fr: 'Documents / Base de connaissances',
        ja: 'ドキュメント / ナレッジベース',
        ko: '문서 / 지식베이스',
        'zh-Hant': '文件 / 知識庫',
      }),
      ocr: t({
        en: 'OCR',
        'zh-Hans': '文字识别',
        fr: 'OCR',
        ja: 'OCR',
        ko: 'OCR',
        'zh-Hant': '文字識別',
      }),
      canvas: t({
        en: 'Canvas',
        'zh-Hans': '画布',
        fr: 'Canevas',
        ja: 'キャンバス',
        ko: '캔버스',
        'zh-Hant': '畫布',
      }),
      dashboards: t({
        en: 'Dashboards',
        'zh-Hans': '仪表板',
        fr: 'Tableaux de bord',
        ja: 'ダッシュボード',
        ko: '대시보드',
        'zh-Hant': '儀表板',
      }),
      admin: t({
        en: 'Admin',
        'zh-Hans': '管理',
        fr: 'Admin',
        ja: '管理',
        ko: '관리',
        'zh-Hant': '管理',
      }),
      adminPanel: t({
        en: 'Admin Panel',
        'zh-Hans': '管理面板',
        fr: 'Panneau admin',
        ja: '管理パネル',
        ko: '관리 패널',
        'zh-Hant': '管理面板',
      }),
    },
    userMenu: {
      workspace: t({
        en: 'Workspace',
        'zh-Hans': '工作空间',
        fr: 'Espace de travail',
        ja: 'ワークスペース',
        ko: '작업 공간',
        'zh-Hant': '工作空間',
      }),
      account: t({
        en: 'Account',
        'zh-Hans': '账户',
        fr: 'Compte',
        ja: 'アカウント',
        ko: '계정',
        'zh-Hant': '帳戶',
      }),
      organization: t({
        en: 'Organization',
        'zh-Hans': '组织',
        fr: 'Organisation',
        ja: '組織',
        ko: '조직',
        'zh-Hant': '組織',
      }),
      preferences: t({
        en: 'Preferences',
        'zh-Hans': '偏好设置',
        fr: 'Préférences',
        ja: '設定',
        ko: '환경설정',
        'zh-Hant': '偏好設定',
      }),
      billing: t({
        en: 'Billing',
        'zh-Hans': '计费',
        fr: 'Facturation',
        ja: '請求',
        ko: '결제',
        'zh-Hant': '計費',
      }),
      plans: t({
        en: 'Plans & subscription',
        'zh-Hans': '方案与订阅',
        fr: 'Plans et abonnement',
        ja: 'プランとサブスクリプション',
        ko: '플랜 및 구독',
        'zh-Hant': '方案與訂閱',
      }),
      billingAndInvoices: t({
        en: 'Billing & invoices',
        'zh-Hans': '计费与发票',
        fr: 'Facturation et factures',
        ja: '請求と請求書',
        ko: '결제 및 청구서',
        'zh-Hant': '計費與發票',
      }),
      logout: t({
        en: 'Log out',
        'zh-Hans': '退出登录',
        fr: 'Déconnexion',
        ja: 'ログアウト',
        ko: '로그아웃',
        'zh-Hant': '登出',
      }),
    },
    titles: {
      documents: t({
        en: 'Documents / KB',
        'zh-Hans': '文档 / 知识库',
        fr: 'Documents / Base de connaissances',
        ja: 'ドキュメント / ナレッジベース',
        ko: '문서 / 지식베이스',
        'zh-Hant': '文件 / 知識庫',
      }),
      claudeChat: t({
        en: 'Kin',
        'zh-Hans': 'Kin',
        fr: 'Kin',
        ja: 'Kin',
        ko: 'Kin',
        'zh-Hant': 'Kin',
      }),
      chat: t({
        en: 'Chat',
        'zh-Hans': '聊天',
        fr: 'Chat',
        ja: 'チャット',
        ko: '채팅',
        'zh-Hant': '聊天',
      }),
      imageChat: t({
        en: 'Image Chat',
        'zh-Hans': '图片聊天',
        fr: 'Chat image',
        ja: '画像チャット',
        ko: '이미지 채팅',
        'zh-Hant': '圖片聊天',
      }),
      workflow: t({
        en: 'Workflow',
        'zh-Hans': '工作流',
        fr: 'Workflow',
        ja: 'ワークフロー',
        ko: '워크플로우',
        'zh-Hant': '工作流',
      }),
      dashboard: t({
        en: 'Dashboard',
        'zh-Hans': '仪表板',
        fr: 'Tableau de bord',
        ja: 'ダッシュボード',
        ko: '대시보드',
        'zh-Hant': '儀表板',
      }),
      skills: t({
        en: 'Skills',
        'zh-Hans': '技能',
        fr: 'Skills',
        ja: 'スキル',
        ko: '스킬',
        'zh-Hant': '技能',
      }),
      agent: t({
        en: 'Agent',
        'zh-Hans': '智能体',
        fr: 'Agent',
        ja: 'エージェント',
        ko: '에이전트',
        'zh-Hant': '智能體',
      }),
      billing: t({
        en: 'Billing',
        'zh-Hans': '计费',
        fr: 'Facturation',
        ja: '請求',
        ko: '결제',
        'zh-Hant': '計費',
      }),
      billingSettings: t({
        en: 'Billing Settings',
        'zh-Hans': '计费设置',
        fr: 'Paramètres de facturation',
        ja: '請求設定',
        ko: '결제 설정',
        'zh-Hant': '計費設定',
      }),
    },
    buttons: {
      signIn: t({
        en: 'Sign In',
        'zh-Hans': '登录',
        fr: 'Connexion',
        ja: 'ログイン',
        ko: '로그인',
        'zh-Hant': '登入',
      }),
      agentChat: t({
        en: 'Open Agent',
        'zh-Hans': '开启智能体',
        fr: "Ouvrir l'agent",
        ja: 'エージェントを開く',
        ko: '에이전트 열기',
        'zh-Hant': '開啟智能體',
      }),
      signUp: t({
        en: 'Sign Up',
        'zh-Hans': '注册',
        fr: 'Créer un compte',
        ja: '新規登録',
        ko: '회원가입',
        'zh-Hant': '註冊',
      }),
      signOut: t({
        en: 'Sign Out',
        'zh-Hans': '退出登录',
        fr: 'Déconnexion',
        ja: 'ログアウト',
        ko: '로그아웃',
        'zh-Hant': '登出',
      }),
      save: t({
        en: 'Save',
        'zh-Hans': '保存',
        fr: 'Enregistrer',
        ja: '保存',
        ko: '저장',
        'zh-Hant': '儲存',
      }),
      cancel: t({
        en: 'Cancel',
        'zh-Hans': '取消',
        fr: 'Annuler',
        ja: 'キャンセル',
        ko: '취소',
        'zh-Hant': '取消',
      }),
      submit: t({
        en: 'Submit',
        'zh-Hans': '提交',
        fr: 'Envoyer',
        ja: '送信',
        ko: '제출',
        'zh-Hant': '提交',
      }),
      delete: t({
        en: 'Delete',
        'zh-Hans': '删除',
        fr: 'Supprimer',
        ja: '削除',
        ko: '삭제',
        'zh-Hant': '刪除',
      }),
      edit: t({
        en: 'Edit',
        'zh-Hans': '编辑',
        fr: 'Modifier',
        ja: '編集',
        ko: '편집',
        'zh-Hant': '編輯',
      }),
      close: t({
        en: 'Close',
        'zh-Hans': '关闭',
        fr: 'Fermer',
        ja: '閉じる',
        ko: '닫기',
        'zh-Hant': '關閉',
      }),
      back: t({
        en: 'Back',
        'zh-Hans': '返回',
        fr: 'Retour',
        ja: '戻る',
        ko: '뒤로',
        'zh-Hant': '返回',
      }),
      next: t({
        en: 'Next',
        'zh-Hans': '下一步',
        fr: 'Suivant',
        ja: '次へ',
        ko: '다음',
        'zh-Hant': '下一步',
      }),
      previous: t({
        en: 'Previous',
        'zh-Hans': '上一步',
        fr: 'Précédent',
        ja: '前へ',
        ko: '이전',
        'zh-Hant': '上一步',
      }),
      confirm: t({
        en: 'Confirm',
        'zh-Hans': '确认',
        fr: 'Confirmer',
        ja: '確認',
        ko: '확인',
        'zh-Hant': '確認',
      }),
      refresh: t({
        en: 'Refresh',
        'zh-Hans': '刷新',
        fr: 'Actualiser',
        ja: '更新',
        ko: '새로고침',
        'zh-Hant': '重新整理',
      }),
      loading: t({
        en: 'Loading...',
        'zh-Hans': '加载中...',
        fr: 'Chargement…',
        ja: '読み込み中…',
        ko: '로딩 중…',
        'zh-Hant': '載入中…',
      }),
    },
    meta: {
      title: t({
        en: 'Kin — Self-hosted AI-Agent Workspace',
        'zh-Hans': 'Kin — 自托管 AI-Agent 工作台',
        fr: 'Kin — Espace AI-Agent auto-hébergé',
        ja: 'Kin — セルフホスト型 AI-Agent ワークスペース',
        ko: 'Kin — 셀프호스팅 AI-Agent 워크스페이스',
        'zh-Hant': 'Kin — 自託管 AI-Agent 工作台',
      }),
      description: t({
        en: 'A private, self-hosted AI-Agent workspace for small teams — multi-model on the ARK gateway, fully sandboxed: streaming chat, curated skills, artifacts with live preview, and sessions.',
        'zh-Hans': '面向小团队的私有化 AI-Agent 工作台——基于 ARK 网关多模型、全沙盒：流式对话、精选技能、Artifacts 真预览与会话管理。',
        fr: "Un espace de travail AI-Agent privé et auto-hébergé pour petites équipes — multi-modèle via la passerelle ARK, entièrement isolé : chat en flux, skills sélectionnés, artifacts avec aperçu en direct et sessions.",
        ja: '小さなチーム向けのプライベートなセルフホスト型 AI-Agent ワークスペース——ARK ゲートウェイで多モデル、完全サンドボックス：ストリーミングチャット、厳選スキル、ライブプレビュー付き Artifacts、セッション。',
        ko: '소규모 팀을 위한 프라이빗 셀프호스팅 AI-Agent 워크스페이스——ARK 게이트웨이 멀티모델, 완전 샌드박스: 스트리밍 채팅, 큐레이션 스킬, 라이브 프리뷰 Artifacts, 세션.',
        'zh-Hant': '面向小團隊的私有化 AI-Agent 工作台——基於 ARK 網關多模型、全沙盒：串流對話、精選技能、Artifacts 真預覽與會話管理。',
      }),
      keywords: t({
        en: 'Kin, self-hosted, multi-model, AI Agent, Skills, Artifacts, AI Workspace',
        'zh-Hans': 'Kin, self-hosted, multi-model, AI Agent, Skills, Artifacts, AI Workspace',
        fr: 'Kin, self-hosted, multi-model, AI Agent, Skills, Artifacts, AI Workspace',
        ja: 'Kin, self-hosted, multi-model, AI Agent, Skills, Artifacts, AI Workspace',
        ko: 'Kin, self-hosted, multi-model, AI Agent, Skills, Artifacts, AI Workspace',
        'zh-Hant': 'Kin, self-hosted, multi-model, AI Agent, Skills, Artifacts, AI Workspace',
      }),
    },
    charts: {
      dashboard: t({
        en: 'Dashboard',
        'zh-Hans': '仪表板',
        fr: 'Tableau de bord',
        ja: 'ダッシュボード',
        ko: '대시보드',
        'zh-Hant': '儀表板',
      }),
      dashboardDesc: t({
        en: 'Monitor your key metrics and performance indicators.',
        'zh-Hans': '监控关键指标与表现。',
        fr: 'Suivez vos indicateurs clés.',
        ja: '主要指標とパフォーマンスを確認。',
        ko: '주요 지표와 성과를 확인하세요.',
        'zh-Hant': '監控關鍵指標與表現。',
      }),
      totalRevenue: t({
        en: 'Total Revenue',
        'zh-Hans': '总收入',
        fr: 'Revenus totaux',
        ja: '総収益',
        ko: '총 수익',
        'zh-Hant': '總收入',
      }),
      totalUsers: t({
        en: 'Total Users',
        'zh-Hans': '总用户数',
        fr: 'Utilisateurs totaux',
        ja: '総ユーザー数',
        ko: '총 사용자',
        'zh-Hant': '總用戶數',
      }),
      activeNow: t({
        en: 'Active Now',
        'zh-Hans': '当前活跃',
        fr: 'En ligne maintenant',
        ja: '現在アクティブ',
        ko: '현재 접속 중',
        'zh-Hant': '目前活躍',
      }),
      growthRate: t({
        en: 'Growth Rate',
        'zh-Hans': '增长率',
        fr: 'Taux de croissance',
        ja: '成長率',
        ko: '성장률',
        'zh-Hant': '成長率',
      }),
      overview: t({
        en: 'Overview',
        'zh-Hans': '概览',
        fr: 'Aperçu',
        ja: '概要',
        ko: '개요',
        'zh-Hant': '概覽',
      }),
      overviewDesc: t({
        en: 'Your performance metrics for the current period',
        'zh-Hans': '当前周期表现指标',
        fr: 'Indicateurs de la période en cours',
        ja: '現在期間のパフォーマンス指標',
        ko: '현재 기간 성과 지표',
        'zh-Hant': '目前週期表現指標',
      }),
      recentActivity: t({
        en: 'Recent Activity',
        'zh-Hans': '最近动态',
        fr: 'Activité récente',
        ja: '最近のアクティビティ',
        ko: '최근 활동',
        'zh-Hant': '最近動態',
      }),
      recentActivityDesc: t({
        en: 'Latest updates and transactions',
        'zh-Hans': '最新动态与交易',
        fr: 'Dernières mises à jour et transactions',
        ja: '最新の更新と取引',
        ko: '최신 업데이트 및 거래',
        'zh-Hant': '最新動態與交易',
      }),
    },
    placeholders: {
      exampleCompany: t({
        en: 'e.g., TechCorp',
        'zh-Hans': '例如：TechCorp',
        fr: 'ex. TechCorp',
        ja: '例：TechCorp',
        ko: '예: TechCorp',
        'zh-Hant': '例如：TechCorp',
      }),
    },
    common: {
      appName: t({
        en: 'Kin',
        'zh-Hans': 'Kin',
        fr: 'Kin',
        ja: 'Kin',
        ko: 'Kin',
        'zh-Hant': 'Kin',
      }),
      welcome: t({
        en: 'Welcome',
        'zh-Hans': '欢迎',
        fr: 'Bienvenue',
        ja: 'ようこそ',
        ko: '환영합니다',
        'zh-Hant': '歡迎',
      }),
      welcomeTo: t({
        en: 'Welcome to {name}',
        'zh-Hans': '欢迎使用 {name}',
        fr: 'Bienvenue sur {name}',
        ja: '{name} へようこそ',
        ko: '{name}에 오신 것을 환영합니다',
        'zh-Hant': '歡迎使用 {name}',
      }),
      redirectingToAgentChat: t({
        en: 'Opening Agent…',
        'zh-Hans': '正在开启智能体…',
        fr: "Ouverture de l'agent…",
        ja: 'エージェントを開いています…',
        ko: '에이전트를 여는 중…',
        'zh-Hant': '正在開啟智能體…',
      }),
      error: t({
        en: 'Error',
        'zh-Hans': '错误',
        fr: 'Erreur',
        ja: 'エラー',
        ko: '오류',
        'zh-Hant': '錯誤',
      }),
      success: t({
        en: 'Success',
        'zh-Hans': '成功',
        fr: 'Succès',
        ja: '成功',
        ko: '성공',
        'zh-Hant': '成功',
      }),
      warning: t({
        en: 'Warning',
        'zh-Hans': '警告',
        fr: 'Attention',
        ja: '警告',
        ko: '경고',
        'zh-Hant': '警告',
      }),
      info: t({
        en: 'Info',
        'zh-Hans': '信息',
        fr: 'Info',
        ja: '情報',
        ko: '정보',
        'zh-Hant': '資訊',
      }),
    },
  },
  key: 'app',
} satisfies Dictionary;

export default appContent;
